# Generated by Django 4.1.2 on 2022-10-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=70)),
                ('img_url', models.CharField(max_length=255)),
                ('genre_description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('img_url', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtube')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('link', models.URLField()),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtube')),
            ],
        ),
    ]
