# Generated by Django 4.1.2 on 2022-10-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notables',
            new_name='Notable',
        ),
    ]
